name: file_cloud
description: A cloud filesystem abstraction layer for Dart, providing unified access to cloud storage providers like MinIO and S3-compatible services.
version: 0.1.0
repository: https://github.com/kingwill101/storage_fs/tree/master/pkgs/file_cloud
resolution: workspace

topics:
  - cloud-storage
  - filesystem
  - minio
  - s3-compatible

homepage: https://github.com/kingwill101/storage_fs/tree/master/pkgs/file_cloud

issue_tracker: https://github.com/kingwill101/storage_fs/issues

funding:
  - https://www.buymeacoffee.com/kingwill101
environment:
  sdk: ">=3.9.0<4.0.0"

dependencies:
  file: ^7.0.1
  minio: ^3.5.8
  path: ^1.9.1
  http: ^1.5.0
  meta: ^1.17.0
  crypto: ^3.0.6
  mime: ^2.0.0
  convert: ^3.1.2
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
