name: file_cloud
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
resolution: workspace
environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  file: ^7.0.1
  minio: ^3.5.8
  path: ^1.9.1
  http: ^1.5.0
  meta: ^1.17.0
  crypto: ^3.0.6
  mime: ^2.0.0
  convert: ^3.1.2
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
