name: storage_fs
description: A comprehensive filesystem abstraction for Dart, inspired by Laravel's Storage facade. Supports both local and cloud storage with a unified API.
version: 0.1.0
repository: https://github.com/kingwill101/storage_fs/tree/master/pkgs/storage_fs
resolution: workspace

topics:
  - filesystem
  - storage
  - abstraction
  - cloud-storage

homepage: https://github.com/kingwill101/storage_fs/tree/master/pkgs/storage_fs

issue_tracker: https://github.com/kingwill101/storage_fs/issues

funding:
  - https://www.buymeacoffee.com/kingwill101
environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  file: ^7.0.1
  path: ^1.9.1
  meta: ^1.17.0
  crypto: ^3.0.6
  mime: ^2.0.0
  convert: ^3.1.2
  file_cloud: ^0.1.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
